name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    if: false
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Get used callsigns
        run: ./get-used.sh
      - name: Generate free callsign files
        run: node generate-free.js
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Upload static files as artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: callsign-free
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
